version: "3.7"
services:
  service-mysql:
    volumes:
      - service-mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  service-clean-arch:
    ports:
      - "9230:9229"
    build:
      context: ./service-clean-arch
      dockerfile: Dockerfile
    volumes:
      - ./service-clean-arch/code:/app

  service-mongodb:
    build:
      context: ./service-mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"

volumes:
  service-mysql-volume:
    driver: local
